[BUILDFIX] ipopt-sfe: temporally disable build
Since we have not obtained academic licenses for HSL for Ipopt:

Linking CXX executable GlobalCorrectionReal
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `ma27id_'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `ma28ad_'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `ma27ad_'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `mc19ad_'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `ma27cd_'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libipopt.so: undefined reference to `ma27bd_'